name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        tag: "m"
        commit: "master"
